- name: Configure GRUB to enable serial console
  ansible.builtin.copy:
    src: grub
    dest: /etc/default/grub
    mode: '0644'
    owner: root
    group: root
    backup: no

- name: Regenerate GRUB configuration
  ansible.builtin.command: "/usr/sbin/grub-mkconfig -o /boot/grub/grub.cfg"

- name: Network config
  ansible.builtin.copy:
    src: interfaces
    dest: /etc/network/interfaces
    mode: '0644'
    owner: root
    group: root
    backup: no

- name: Create .ssh directory for root
  ansible.builtin.file:
    path: /root/.ssh
    state: directory

- name: Copy authorized_keys for root
  ansible.builtin.copy:
    src: authorized_keys
    dest: /root/.ssh/authorized_keys

- name: Update apt cache and upgrade packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install common packages
  ansible.builtin.apt:
    name: 
      - jq
      - curl
      - wget
      - vim 
      - git 
      - ansible 
      - keychain 
      - tmux 
      - python3
      - logrotate
      - net-tools
      - build-essential 
      - procps 
      - file
      - gpg
      - sudo
    state: latest
